[package]
name = "pich8"
version = "0.1.0"
authors = ["Philipp W <phil.w07@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
bitvec = { version = "0.19.3", features = ["serde"] }
getset = "0.1.1"
serde = { version = "1.0.117", features = ["derive"] }
rmp-serde = "0.14.4"
glium = "0.27.0"
imgui = "0.5.0"
imgui-glium-renderer = "0.5.0"
imgui-winit-support = "0.5.0"
tinyfiledialogs = "3.3.10"
rodio = "0.13.0"
getopts = "0.2.21"
url = "2.2.0"
reqwest = { version = "0.10.8", features = ["blocking"] }
