[package]
name = "pich8"
version = "1.0.1"
description = "A cross-platform CHIP-8, SUPER-CHIP and XO-CHIP interpreter and debugger written in Rust"
authors = ["Philipp W <phil.w07@gmail.com>"]
edition = "2018"
build = "build.rs"
license = "MIT"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"

[dependencies]
rand = "0.7.3"
serde = { version = "1.0.118", features = ["derive"] }
rmp-serde = "0.15.0"
glium = "0.28.0"
imgui = "0.6.1"
imgui-glium-renderer = "0.6.0"
imgui-winit-support = "0.6.0"
tinyfiledialogs = "3.3.10"
rodio = "0.13.0"
getopts = "0.2.21"
url = { version = "2.2.0", optional = true }
reqwest = { version = "0.10.10", features = ["blocking"], optional = true }
image = "0.23.12"

[features]
default = ["rom-download"]
rom-download = ["url", "reqwest"]
