[package]
name = "pich8"
version = "0.1.0"
authors = ["Philipp W <phil.w07@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
bitvec = { version = "0.19.3", features = ["serde"] }
getset = "0.1.1"
serde = { version = "1.0.117", features = ["derive"] }
rmp-serde = "0.14.4"
sdl2 = "0.34.3"
spin_sleep = "1.0.0"

[features]
static-link = ["sdl2/static-link"]
